"""initial schema

Revision ID: 4bf075ee2ede
Revises: 
Create Date: 2026-09-15 07:54:36.064054

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Autogenerate renders the UTCDateTime TypeDecorator by qualified name.
import octave.db.models.base


revision: str = '4bf075ee2ede'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('model_tag', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', octave.db.models.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcp_servers',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('transport', sa.Text(), nullable=False),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('env', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', octave.db.models.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', octave.db.models.base.UTCDateTime(), nullable=False),
    sa.CheckConstraint("(transport = 'stdio' AND command IS NOT NULL AND url IS NULL) OR (transport = 'http' AND url IS NOT NULL AND command IS NULL)", name='ck_mcp_servers_transport_shape'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_mcp_servers_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('created_at', octave.db.models.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=False),
    sa.CheckConstraint('(user_id IS NULL) != (agent_id IS NULL)', name='ck_participants_exactly_one_identity'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', name='uq_participants_agent'),
    sa.UniqueConstraint('user_id', name='uq_participants_user')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.Text(), nullable=False),
    sa.Column('parent_session_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', octave.db.models.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', octave.db.models.base.UTCDateTime(), nullable=False),
    sa.Column('ended_at', octave.db.models.base.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_created_by_user', ['created_by_user_id'], unique=False)
        batch_op.create_index('ix_sessions_parent', ['parent_session_id'], unique=False)

    op.create_table('vault_items',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=True),
    sa.Column('embedding_dim', sa.Integer(), nullable=True),
    sa.Column('created_at', octave.db.models.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', octave.db.models.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vault_items', schema=None) as batch_op:
        batch_op.create_index('ix_vault_items_user_kind', ['user_id', 'kind'], unique=False)

    op.create_table('session_participants',
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('participant_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('joined_at', octave.db.models.base.UTCDateTime(), nullable=False),
    sa.Column('left_at', octave.db.models.base.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'participant_id', name='pk_session_participants')
    )
    op.create_table('events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('author_participant_id', sa.Text(), nullable=True),
    sa.Column('target_participant_id', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', octave.db.models.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id', 'target_participant_id'], ['session_participants.session_id', 'session_participants.participant_id'], name='fk_events_target_membership', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'seq', name='uq_events_session_seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('session_participants')
    with op.batch_alter_table('vault_items', schema=None) as batch_op:
        batch_op.drop_index('ix_vault_items_user_kind')

    op.drop_table('vault_items')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_parent')
        batch_op.drop_index('ix_sessions_created_by_user')

    op.drop_table('sessions')
    op.drop_table('participants')
    op.drop_table('users')
    op.drop_table('mcp_servers')
    op.drop_table('agents')
    # ### end Alembic commands ###
